balance_controller:
  virtual_model_controller:
    heading:
      kp: 600
      kd: 10
      kff: 1
    lateral:
      kp: 1000
      kd: 10
      kff: 1
    vertical:
      kp: 1000
      kd: 10
      kff: 1
    roll:
      kp: 200
      kd: 20
      kff: 0.2
    pitch:
      kp: 400
      kd: 80
      kff: 0.2
    yaw:
      kp: 200
      kd: 50
      kff: 1
    gravity_compensation_percentage: 1.15
  contact_force_distribution:
    weights:
      force:
        heading: 1
        lateral: 1
        vertical: 1
      torque:
        roll: 20
        pitch: 20
        yaw: 5
      regularizer:
        value: 0.00001
      force_diff:
        value: 1
        is_use: false
    constraints:
      friction_coefficient: 0.6
      minimal_normal_force: 10
      load_factor: 1
single_leg_controller:
  x_direction:
    kp: 800
    kd: 20
  y_direction:
    kp: 800
    kd: 20
  z_direction:
    kp: 800
    kd: 80
